# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpG1Ws-nMxMVEZJW6dCkm84rju958-mm
"""

def vinos(l):
    res = 0
    mod = 0
    for i in range(len(l)):
        mod = mod+l[i]
        res += abs(mod)
    return res

n = 0
lista = []

while (n==0):
    c = int(input())
    if c != 0:
        l = list(map(int,input().split()))
        lista.append(l)
    else:
        n = 1

for i in range(len(lista)):
    print(vinos(lista[i]))